<h1>Hellow I am Contact Page</h1>


<a href="{{url('/')}}">Home</a>|
<a href="{{URL::to('/faq')}}">FAQ</a>|
<a href="{{route('con')}}">Contact</a>|

<p>
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Hic doloremque ipsa tenetur laudantium ex! Cupiditate id animi delectus sint voluptate aliquid molestiae, amet nesciunt quae sequi corrupti consequuntur deleniti vitae velit fuga ipsum accusantium quam officiis distinctio. Possimus sint commodi aspernatur corporis nihil debitis perspiciatis sequi magni, quia deleniti vel tempore? In possimus consectetur et eligendi consequatur ipsum esse, totam est odio magni blanditiis non quaerat incidunt voluptatibus perferendis itaque quae tenetur. Quo, earum minus voluptate cumque quos explicabo veritatis, quis adipisci illum facilis nisi optio et laudantium, delectus mollitia excepturi sequi pariatur perferendis quia. Nulla praesentium nobis quaerat explicabo repellendus doloremque totam asperiores iusto laudantium sequi, ratione omnis. Vitae nemo ratione fugiat harum velit, assumenda quae reprehenderit, suscipit molestiae voluptates obcaecati, similique voluptas voluptate! Ipsam quo iure qui ipsum est soluta, quisquam magnam reiciendis praesentium numquam alias saepe amet nobis vel at dolor explicabo. Libero, aperiam! Perspiciatis accusamus dolorum quod aut, eius est ea enim omnis minus dolores accusantium ratione nisi quidem praesentium fugit? Nam sapiente ex harum voluptatibus, inventore aliquam eligendi, at veritatis blanditiis exercitationem, labore id. Molestias unde, quam doloribus sequi repudiandae deleniti minima labore ullam? Natus explicabo repellat quas quis. Aut repudiandae ullam corporis tempora. Pariatur culpa accusamus error perferendis incidunt quos commodi laboriosam non sint earum atque fugiat velit accusantium dicta cum veritatis id saepe, nam labore voluptatum ut omnis! Voluptas, hic. Doloribus, error sapiente quo autem dicta perferendis tenetur deserunt ullam quam non quis. Harum deleniti iure distinctio sunt dolores vero. Sunt alias deserunt aliquam similique quae, in possimus quis aliquid corrupti hic odit voluptatem at reiciendis explicabo, tempora fugiat labore perferendis. Deleniti facilis quasi eum, dolor impedit minus quas earum doloremque, aperiam voluptates nulla quaerat enim optio? Qui enim ex dolor reprehenderit, adipisci aliquid neque eos itaque accusantium harum iure, cum tenetur repellendus. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores corporis minus qui, molestiae doloremque optio aperiam rerum odit nostrum. Maxime rem, vero atque at hic ratione amet culpa perferendis dicta!
</p>